apiVersion: v1
kind: Service
metadata:
  name: {{ template "application.name" . }}
  labels:
    app: {{ template "application.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    appVersion: {{ .Values.appVersion | quote }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type:  ClusterIP
  ports:
    - port: 8080
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ template "application.name" . }}
    release: {{ .Release.Name }}
